### PR TITLE
12.0 migr

### PR DESCRIPTION
**Pull request by bguillot**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@bguillot Do you plan to fix this PR ?

I have an error with storage_image_product on tests/common.py :

https://github.com/akretion/storage/pull/64/files#diff-baad28496f3ab55c7f4509568cc8b6d7R15

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by rousseldenis** [comment]
> @bguillot Do you plan to fix this PR ?
> 
> I have an error with storage_image_product on tests/common.py :
> 
> https://github.com/akretion/storage/pull/64/files#diff-baad28496f3ab55c7f4509568cc8b6d7R15
> 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In _get_image function, this works :

```python
        with open(os.path.join(path, "static", name), 'rb') as f:
            content = base64.b64encode(f.read())
        return content
```

open with reading as bytes and a with statement which is, IMHO, more correct

**Comment by rousseldenis** [comment]
https://github.com/akretion/storage/pull/66

**Comment by rousseldenis** [comment]
@bguillot Don't you mind if I restart this one as it appears there are so much changes to do to get the whole repo for v12 working ?

**Comment by bguillot** [comment]
@rousseldenis Yes you can restart it.

**Comment by rousseldenis** [comment]
@bguillot Is it planned to move to OCA/storage ?

**Comment by lmignon** [comment]
Migration done in others PRs...

**Pull request closed without merging**
