### PR TITLE
[11.0][MIG] storage_backend_sftp

### PR DESCRIPTION
**Pull request by bodedra**
Depends on:
----------------

- [ ] https://github.com/akretion/storage/pull/41

### CODE REVIEW

**Comment by bodedra** [comment]
Travis fails due to not setup keychain account. Would you suggest me, what will be possible ways to make it green ?

CC @max3903

**Comment by max3903** [comment]
@bodedra Can you check on version 10 and do the same? Checks are green there.

**Comment by max3903** [comment]
:+1:

**Review by max3903 — APPROVED** [review]

**Comment by florian-dacosta** [comment]
@bodedra Thanks for the migration
I will close this as we are going to port the modules to version 12, and then backport it to towards version 11.

**Pull request closed without merging**
