### PR TITLE
[12.0][FIX] storage_product_image: Fix bytes reading in tests

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@bguillot @sebastienbeau @lmignon

**Review by rvalyi — APPROVED** [review]
https://stackoverflow.com/a/42340744

**Review by bguillot — APPROVED** [review]
Code review.
Thank you.

**Comment by rousseldenis** [comment]
I've just fixed pre-commit errors in separate commit

**Comment by rousseldenis** [comment]
Closing as new migrations

**Pull request closed without merging**
